name: Update Version and Build

on:
  workflow_dispatch:
    inputs:
      version-specifier:
        description: 'Version to update (major/minor/patch)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Validate input
      run: |
        if [[ "${{ github.event.inputs.version-specifier }}" != "major" && "${{ github.event.inputs.version-specifier }}" != "minor" && "${{ github.event.inputs.version-specifier }}" != "patch" ]]; then
          echo "Error: Invalid version input. Allowed values are 'major', 'minor', and 'patch'."
          exit 1
        fi

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - uses: ./.github/actions/setup

    - name: Update package.json version
      id: update-version
      run: |
        pnpm version ${{ github.event.inputs.version-specifier }}
        node -e 'console.log("version="+require("./package.json").version)' >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update version to ${{ steps.update-version.outputs.version }}
        commit-message: Update version to ${{ steps.update-version.outputs.version }}
        body: "This pull request updates the version to ${{ steps.update-version.outputs.version }}."
        branch: version-${{ steps.update-version.outputs.version }}
        base: main
        draft: false
